#bridge-file-version: #21
#for blocks found naturally
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 dirt 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 dirt 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gravel 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 grass 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 coal_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 iron_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 lapis_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gold_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 diamond_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 emerald_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sand 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sandstone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sand 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 mycelium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 snow 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 snow_layer 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 blue_ice 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 netherrack 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 soul_sand 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 nether_gold_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 ancient_debris 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 magma 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 blackstone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_nylium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 nether_wart_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_nylium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_wart_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 soul_soil 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 basalt 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 obsidian 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crying_obsidian 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 end_stone 0 tp @s ~ ~ ~
#for blocks usually placed by players or generated in structures
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_planks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_planks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wooden_slab 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_wooden_slab 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_double_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_double_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_crimson_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_crimson_stem 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_crimson_stem 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_dark_oak_log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_dark_oak_log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_dark_oak_log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_jungle_log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_jungle_log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_jungle_log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_oak_log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_oak_log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_oak_log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_spruce_log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_spruce_log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_spruce_log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_warped_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_warped_stem 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_warped_stem 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wood 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_hyphae 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_hyphae 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_crimson_hyphae 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stripped_warped_hyphae 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 melon_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pumpkin 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 carved_pumpkin 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 carved_pumpkin 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 carved_pumpkin 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 carved_pumpkin 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 cobblestone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 mossy_cobblestone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stonebrick 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stonebrick 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stonebrick 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stonebrick 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone_bricks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 cracked_polished_blackstone_bricks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 monster_egg 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brick_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab2 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab2 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab3 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab3 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone_brick_slab 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 polished_blackstone_brick_slab 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone_slab4 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab4 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab4 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab4 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab4 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 double_stone_slab4 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 prismarine 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 prismarine 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 prismarine 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 nether_brick 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 cracked_nether_bricks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 chiseled_nether_bricks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_nether_brick 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 piston 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pistonarmcollision 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sticky_piston 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stickypistonarmcollision 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 wool 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 black_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 blue_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 cyan_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gray_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 green_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 light_blue_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 lime_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 magenta_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 orange_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 pink_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 purple_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 silver_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 white_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 yellow_glazed_terracotta 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 end_stone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 end_bricks 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 purpur_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 purpur_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_block 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 coal_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 iron_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gold_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 lapis_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 diamond_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 emerald_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 netherite_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 redstone_block 0 tp @s ~ ~ ~