clear @a rift:wooden_chair
clear @a rift:plastic_chair
clear @a rift:wooden_table
clear @a rift:plastic_table
clear @a rift:glass_table
clear @a rift:sofa
clear @a rift:wooden_bench
clear @a rift:plastic_bench
clear @a rift:wooden_spiked_wall
clear @a rift:metal_spiked_wall