tag @e remove tyrannosaurusRoar
tag @e remove trikeCharge
tag @e remove utahBuff
tag @e remove stegoHarvest
tag @e remove climbMount
tag @e remove nClimbMount
tag @e remove utahBuffEffects
tag @e remove nUtahBuffEffects
tag @e remove trikeHarvest
tag @e remove apatoHarvest
tag @e remove apatoCannonFire
tag @e remove apatoMortarFire
tag @e remove apatoCatapultLaunch
tag @e remove apatoAddRiders
tag @e remove apatoRemoveRiders
tag @e remove apatoTailWhip
tag @e remove parasaurHarvest
tag @e remove parasaurCallScare
tag @e remove parasaurCallAggravate
tag @e remove sarcoSpin
tag @e remove anomaloInvisible
tag @e remove carrying