#bridge-file-version: #21
#for blocks found naturally
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 dirt 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 dirt 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gravel 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 grass 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stone 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 coal_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 iron_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 lapis_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 gold_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 diamond_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 emerald_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sand 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sandstone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 sand 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 stained_hardened_clay 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 11 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 12 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 13 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 14 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 log2 15 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 mycelium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 brown_mushroom_block 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 1 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 2 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 3 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 4 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 5 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 6 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 8 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 9 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 red_mushroom_block 10 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 snow 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 snow_layer 7 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 blue_ice 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 netherrack 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 soul_sand 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 quartz_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 nether_gold_ore 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 ancient_debris 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 magma 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 blackstone 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_nylium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crimson_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 nether_wart_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_nylium 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_stem 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 warped_wart_block 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 soul_soil 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 basalt 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 obsidian 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 crying_obsidian 0 tp @s ~ ~ ~
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 end_stone 0 tp @s ~ ~ ~
#for blocks usually placed by players or generated in structures
execute @e[tag=climber, r=2] ~ ~ ~ detect ^ ^ ^+1 planks 0 tp @s ~ ~ ~