execute as @s[tag=!inWater] run event entity @e[type=rift:ankylosaurus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=inWater] run event entity @e[type=rift:anomalocaris, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:apatosaurus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
event entity @e[type=rift:baryonyx, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:dilophosaurus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:dimetrodon, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:direwolf, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:megaloceros, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
event entity @e[type=rift:sarcosuchus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:saurophaganax, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget, tag=!sleeping] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:stegosaurus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:triceratops, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:tyrannosaurus, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn
execute as @s[tag=!inWater] run event entity @e[type=rift:utahraptor, r=64, tag=tamed, tag=!baby, tag=!sitting, tag=!hunting, tag=!ridden, tag=!hasTarget] rift:aggravated_via_aggravating_horn